### ISSUE TITLE
Make the variable names used for secrets not specific to .NET Docker

### ISSUE THREAD

**Issue by dagood** [dotnet/docker-tools#843]
There are a few variable names that contain `dotnet`--a few sample instances I saw:

https://github.com/dotnet/docker-tools/blob/4967fabfd364a47f2daef20bfba35d57c0e67873/eng/common/templates/jobs/publish.yml#L55

https://github.com/dotnet/docker-tools/blob/4967fabfd364a47f2daef20bfba35d57c0e67873/eng/common/templates/jobs/publish.yml#L38

There are also non-secrets with `dotnet` names like `dotnetDockerHubBot.userName` (not to mention the secret `BotAccount-dotnet-dockerhub-bot-PAT` also on this line):

https://github.com/dotnet/docker-tools/blob/4967fabfd364a47f2daef20bfba35d57c0e67873/eng/common/templates/jobs/copy-base-images.yml#L21

I didn't have to edit `eng/common` to work around this, just defined variables in my pipeline that filled in the undefined variables:

```yml
- name: BotAccount-dotnet-docker-acr-bot-password
  value: $(my-acr-password)
- name: app-dotnetdockerbuild-client-secret
  value: $(my-client-secret)
```

It would be better for future onboarding if these had broader names, to make it clearer where "my" values need to go.

I think it would make sense for `eng/common` to have a variable template that maps the .NET-specific values/secrets, then dotnet/dotnet-docker et. al. can import that in their pipelines. Then this wouldn't cause too much duplication in the multiple .NET repos.
