### ISSUE TITLE
Publish of Image Builder for single OS type fails

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#850]
Now that Image Builder can automatically be rebuilt because of https://github.com/dotnet/docker-tools/pull/834, it's likely that it will be rebuilt for either the Linux or Windows Dockerfile, but unlikely that it would ever rebuild both in the same build due to differences in the base image update times.  If a build is made for just a single OS type, the publish will fail when trying to publish the multi-arch tags.  This is because the multi-arch tag name is generated dynamically, based on the pipeline ID.  

As an example, let's say a build is ran for Dockerfile.windows.  The pipeline ID is 1305496.  The multi-arch tag that gets generated is  `dotnet-buildtools/image-builder:1305496`.  When generating the manifest for that multi-arch tag, it provides the list of underlying image tags that the multi-arch tag is for.  This ends up using `dotnet-buildtools/image-builder:linux-amd64-1305496` and `dotnet-buildtools/image-builder:linux-arm64-1305496` for Linux.  But no Linux images were ever built in this build.  So this ends up failing because the manifest tool is unable to find the images.

**Comment by mthalman** [comment]
Here's my proposal on how to fix this:

* In addition to the current tags, define floating concrete tags for Image Builder.  (Defining a floating multi-arch tag would be optional but it seems like a nice thing to have.)  These tag names should be statically defined.  Examples: `image-builder:latest`, `image-builder:linux-amd64`, `image-builder:nanoserver-1809-amd64`. This provides a known name to be able to reference the latest available image.
* Update the `publishManifest` command to only use statically named tags instead of ones that were generated dynamically with a manifest variable.

This would allow the creation of a manifest spec similar to the following:

```yaml
image: mcr.microsoft.com/test/dotnet-buildtools/image-builder:1305496
manifests:
- image: mcr.microsoft.com/dotnet-buildtools/image-builder:linux-amd64
  platform:
    architecture: amd64
    os: linux
- image: mcr.microsoft.com/dotnet-buildtools/image-builder:linux-arm64v8
  platform:
    architecture: arm64
    os: linux
    variant: v8
- image: mcr.microsoft.com/test/dotnet-buildtools/image-builder:windowsservercore-ltsc2016-amd64
  platform:
    architecture: amd64
    os: windows
- image: mcr.microsoft.com/test/dotnet-buildtools/image-builder:nanoserver-1809-amd64
  platform:
    architecture: amd64
    os: windows
- image: mcr.microsoft.com/test/dotnet-buildtools/image-builder:nanoserver-2004-amd64
  platform:
    architecture: amd64
    os: windows
- image: mcr.microsoft.com/test/dotnet-buildtools/image-builder:nanoserver-20H2-amd64
  platform:
    architecture: amd64
    os: windows
- image: mcr.microsoft.com/test/dotnet-buildtools/image-builder:nanoserver-ltsc2022-amd64
  platform:
    architecture: amd64
    os: windows
```

Notice that there is no pipeline ID used in the tag name of the referenced images except for the definition of the multi-arch tag itself.  This allows for valid and correct image names to be referenced.
